# Generated by Django 3.0a1 on 2019-09-28 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0003_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='album',
        ),
        migrations.AddField(
            model_name='song',
            name='son_logo',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='video',
            name='duration',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='album',
            name='album_logo',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='album',
            name='album_title',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='album',
            name='artist',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='album',
            name='genre',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='song',
            name='album',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='one.Album'),
        ),
        migrations.AlterField(
            model_name='song',
            name='file_type',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='song',
            name='son_title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='video',
            name='file_type',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='video',
            name='son_title',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='one.Song'),
        ),
    ]
