# Generated by Django 3.0a1 on 2019-10-02 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0005_auto_20190928_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='son_logo',
            field=models.FileField(upload_to=''),
        ),
    ]
