# Generated by Django 3.0a1 on 2019-10-04 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0007_auto_20191004_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_logo',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='song',
            name='son_logo',
            field=models.FileField(upload_to=''),
        ),
    ]
