# Generated by Django 3.0a1 on 2019-10-04 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0008_auto_20191004_1050'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default='', max_length=100)),
                ('username', models.CharField(default='', max_length=100)),
                ('password', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
